# src/main/resources/application-dev.yml
spring:
  application:
    name: kouizer
  config:
    activate:
      on-profile: dev
    import: classpath:category-mapping.yml
  datasource:
    # H2 In-Memory Configuration
    url: jdbc:h2:mem:kouizerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  h2:
    # Enable H2 Console at http://localhost:8080/h2-console
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
