# src/main/resources/application-integration.yml
spring:
  application:
    name: kouizer
  config:
    activate:
      on-profile: integration
  datasource:
    # MySQL Configuration
    url: jdbc:mysql://localhost:3306/kouizer?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
    platform: mysql
  jpa:
    # Prevents dropping/recreating tables in production/integration environments
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect